name: Test Deploy

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check secrets
        run: |
          echo "Checking if secrets are set..."
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "ERROR: SSH_PRIVATE_KEY is not set"
            exit 1
          fi
          echo "✓ SSH_PRIVATE_KEY is set"

          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
            echo "ERROR: SERVER_HOST is not set"
            exit 1
          fi
          echo "✓ SERVER_HOST: ${{ secrets.SERVER_HOST }}"

          echo "✓ All secrets OK"

      - name: Test SSH key format
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/test_key
          chmod 600 /tmp/test_key
          ssh-keygen -l -f /tmp/test_key || echo "Invalid key format"
          rm /tmp/test_key
